#!/usr/bin/env Rscript

repos <- "https://cran.rstudio.com"

# yes I know I could have build a cycle, but the following is the product
# if a script itself over the installed packages: so gimme a break.

devtools::install_version("alpaca", version = "0.3.2", repos = repos)
devtools::install_version("assertthat", version = "0.2.1", repos = repos)
devtools::install_version("backports", version = "1.1.5", repos = repos)
devtools::install_version("bife", version = "0.7", repos = repos)
devtools::install_version("blob", version = "1.2.0", repos = repos)
devtools::install_version("callr", version = "3.4.0", repos = repos)
devtools::install_version("cli", version = "2.0.1", repos = repos)
devtools::install_version("cliapp", version = "0.1.0", repos = repos)
devtools::install_version("covr", version = "3.4.0", repos = repos)
devtools::install_version("curl", version = "4.0", repos = repos)
devtools::install_version("daarem", version = "0.5", repos = repos)
devtools::install_version("deSolve", version = "1.28", repos = repos)
devtools::install_version("digest", version = "0.6.23", repos = repos)
devtools::install_version("doParallel", version = "1.0.15", repos = repos)
devtools::install_version("evaluate", version = "0.14", repos = repos)
devtools::install_version("fansi", version = "0.4.1", repos = repos)
devtools::install_version("fastmap", version = "1.0.1", repos = repos)
devtools::install_version("filelock", version = "1.0.2", repos = repos)
devtools::install_version("foreach", version = "1.4.7", repos = repos)
devtools::install_version("formatR", version = "1.7", repos = repos)
devtools::install_version("fs", version = "1.3.1", repos = repos)
devtools::install_version("future", version = "1.15.1", repos = repos)
devtools::install_version("gargle", version = "0.4.0", repos = repos)
devtools::install_version("ggplot2", version = "3.3.0", repos = repos)
devtools::install_version("git2r", version = "0.27.1", repos = repos)
devtools::install_version("glue", version = "1.4.1", repos = repos)
devtools::install_version("googledrive", version = "1.0.0", repos = repos)
devtools::install_version("googlesheets4", version = "0.1.0", repos = repos)
devtools::install_version("GVARX", version = "1.2", repos = repos)
devtools::install_version("highr", version = "0.8", repos = repos)
devtools::install_version("hms", version = "0.5.3", repos = repos)
devtools::install_version("htmltools", version = "0.4.0", repos = repos)
devtools::install_version("httpuv", version = "1.5.2", repos = repos)
devtools::install_version("httr", version = "1.4.1", repos = repos)
devtools::install_version("igraph", version = "1.2.4.2", repos = repos)
devtools::install_version("isoband", version = "0.2.0", repos = repos)
devtools::install_version("iterators", version = "1.0.12", repos = repos)
devtools::install_version("knitr", version = "1.23", repos = repos)
devtools::install_version("later", version = "1.0.0", repos = repos)
devtools::install_version("lifecycle", version = "0.2.0", repos = repos)
devtools::install_version("lobstr", version = "1.1.1", repos = repos)
devtools::install_version("markdown", version = "1.0", repos = repos)
devtools::install_version("mime", version = "0.7", repos = repos)
devtools::install_version("mockery", version = "0.4.2", repos = repos)
devtools::install_version("odbc", version = "1.1.6", repos = repos)
devtools::install_version("openssl", version = "1.4.1", repos = repos)
devtools::install_version("pillar", version = "1.4.6", repos = repos)
devtools::install_version("pkgbuild", version = "1.0.6", repos = repos)
devtools::install_version("pkgcache", version = "1.0.6", repos = repos)
devtools::install_version("pkgconfig", version = "2.0.3", repos = repos)
devtools::install_version("plotly", version = "4.9.2", repos = repos)
devtools::install_version("prettycode", version = "1.1.0", repos = repos)
devtools::install_version("prettyunits", version = "1.1.0", repos = repos)
devtools::install_version("processx", version = "3.4.1", repos = repos)
devtools::install_version("progress", version = "1.2.2", repos = repos)
devtools::install_version("promises", version = "1.1.0", repos = repos)
devtools::install_version("purrr", version = "0.3.3", repos = repos)
devtools::install_version("R6", version = "2.4.1", repos = repos)
devtools::install_version("rcmdcheck", version = "1.3.3", repos = repos)
devtools::install_version("renv", version = "0.10.0", repos = repos)
devtools::install_version("reshape", version = "0.8.8", repos = repos)
devtools::install_version("rex", version = "1.1.2", repos = repos)
devtools::install_version("RJSONIO", version = "1.3-1.3", repos = repos)
devtools::install_version("rlang", version = "0.4.2", repos = repos)
devtools::install_version("rlist", version = "0.4.6.1", repos = repos)
devtools::install_version("rly", version = "1.6.2", repos = repos)
devtools::install_version("Rserve", version = "1.7-3.1", repos = repos)
devtools::install_version("rstudioapi", version = "0.10", repos = repos)
devtools::install_version("R.utils", version = "2.9.0", repos = repos)
devtools::install_version("rversions", version = "2.0.1", repos = repos)
devtools::install_version("sampling", version = "2.8", repos = repos)
devtools::install_version("seastests", version = "0.14.2", repos = repos)
devtools::install_version("shiny", version = "1.4.0.2", repos = repos)
devtools::install_version("shinyWidgets", version = "0.5.1", repos = repos)
devtools::install_version("stargazer", version = "5.2.2", repos = repos)
devtools::install_version("stringi", version = "1.4.4", repos = repos)
devtools::install_version("sys", version = "3.2", repos = repos)
devtools::install_version("tabulizer", version = "0.2.2", repos = repos)
devtools::install_version("tabulizerjars", version = "1.0.1", repos = repos)
devtools::install_version("tempdisagg", version = "0.25.0", repos = repos)
devtools::install_version("testthat", version = "2.3.1", repos = repos)
devtools::install_version("tibble", version = "2.1.3", repos = repos)
devtools::install_version("usethis", version = "1.5.1", repos = repos)
devtools::install_version("uuid", version = "0.1-2", repos = repos)
devtools::install_version("vctrs", version = "0.2.1", repos = repos)
devtools::install_version("warp", version = "0.1.0", repos = repos)
devtools::install_version("xfun", version = "0.8", repos = repos)
devtools::install_version("XML", version = "3.98-1.20", repos = repos)
devtools::install_version("zoo", version = "1.8-6", repos = repos)

devtools::install_github("giupo/rprogressbar")
devtools::install_github("giupo/rdataset")
devtools::install_github("giupo/RPostgreSQL2")
devtools::install_github("giupo/rutils")
